### ISSUE TITLE
Bot Module Information

### ISSUE THREAD

**Issue by BillChirico** [BillChirico/Volvox.Helios#13]
Information for a Bot Module
1. Name
2. Info
3. Version

Ideally the information should be in a configuration file that is loaded on startup.

The Module information should be shown in the following places:
- Settings
- Logging
- About Page

**Comment by SolarysDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Module Metadata (Solarys)](https://trello.com/c/jWLRyvPr/2-module-metadata-solarys)
