### ISSUE TITLE
Stream Announcer Settings

### ISSUE THREAD

**Issue by BillChirico** [BillChirico/Volvox.Helios#20]

**Comment by Proboarder82** [comment]
I am having an issue with Volvox and the streaming announcement. I have gone into my dashboard and completed everything how I wanted it to be, added a streaming role, have it remove the stream when they go offline I think that it has been great. I decided that I wanted to change the channel to which the announcement goes to. So I changed it in the settings and clicked save. Now it announces the streamer to both channels and it's frustrating me. I have turned the streamer announcement off then back on with the settings that I want to the new channel I want and it remembers and still announces to the original channel and the new channel. How can I get the announcement to stop announcing to both channels and only the one I want it to?

**Comment by BillChirico** [comment]
@Proboarder82 Head back to your dashboard and select the channel you don't want it in then turn that specific channel off and save your settings.
